export * from './Detail'
export * from './Home'
export * from './Login'
export * from './Movie'
export * from './NotFound'
export * from './Register'
export * from './SearchResult'
export * from './Tv'
